thesis/urls.py
from django.urls import path
from .views import ErrorPageView, InstituteDeleteView, InstituteUpdateView, LanguageDeleteView, PersonDeleteView, SubjectDeleteView, ThesisDeleteView, UniversityDeleteView, InstituteCreateView, LanguageCreateView, LanguageUpdateView, PersonCreateView, PersonUpdateView, SubjectCreateView, SubjectUpdateView, UniversityCreateView, UniversityUpdateView, main, search_view, ThesisCreateView, ThesisUpdateView
from thesis import views
from django.contrib.auth import views as auth_views

app_name = 'thesis'

urlpatterns = [
    
    path('', search_view, name='search'),
    path('main/', main, name='main'),
    # path('login/', login_view, name='login'),
    path("accounts/login/", auth_views.LoginView.as_view()),
    path('signup/', views.sign_up, name='sign_up'),
    path('institute/', views.InstituteListView.as_view(), name='institute-list'),
    path('institute/<int:pk>/', views.InstituteDetailView.as_view(), name='institute-detail'),

    path('language/', views.LanguageListView.as_view(), name='language-list'),
    path('language/<int:pk>/', views.LanguageDetailView.as_view(), name='language-detail'),

    path('person/', views.PersonListView.as_view(), name='person-list'),
    path('person/<int:pk>/', views.PersonDetailView.as_view(), name='person-detail'),

    path('subject/', views.SubjectListView.as_view(), name='subject-list'),
    path('subject/<int:pk>/', views.SubjectDetailView.as_view(), name='subject-detail'),

    path('thesis/', views.ThesisListView.as_view(), name='thesis-list'),
    path('thesis/<int:pk>/', views.ThesisDetailView.as_view(), name='thesis-detail'),

    path('thesiskeyword/', views.ThesisKeywordListView.as_view(), name='thesiskeyword-list'),
    path('thesiskeyword/<int:pk>/', views.ThesisKeywordDetailView.as_view(), name='thesiskeyword-detail'),

    path('thesissubject/', views.ThesisSubjectListView.as_view(), name='thesissubject-list'),
    path('thesissubject/<int:pk>/', views.ThesisSubjectDetailView.as_view(), name='thesissubject-detail'),

    path('type/', views.TypeListView.as_view(), name='type-list'),
    path('type/<int:pk>/', views.TypeDetailView.as_view(), name='type-detail'),

    path('university/', views.UniversityListView.as_view(), name='university-list'),
    path('university/<int:pk>/', views.UniversityDetailView.as_view(), name='university-detail'),
    path('search/', search_view, name='search'),

    path('thesis/add/', ThesisCreateView.as_view(), name='thesis_add'),
    path('thesis/<int:pk>/edit/', ThesisUpdateView.as_view(), name='thesis_edit'),
    path('thesis/<int:pk>/delete/', ThesisDeleteView.as_view(), name='thesis_delete'),

    path('person/add', PersonCreateView.as_view(), name='person_add'),
    path('person/<int:pk>/edit/', PersonUpdateView.as_view(), name='person_edit'),
    path('person/<int:pk>/delete/', PersonDeleteView.as_view(), name='person_delete'),

    path('university/add', UniversityCreateView.as_view(), name='university_create'),
    path('university/<int:pk>/edit', UniversityUpdateView.as_view(), name='university_update'),
    path('university/<int:pk>/delete', UniversityDeleteView.as_view(), name='university_delete'),

    path('institute/add', InstituteCreateView.as_view(), name='institute_create'),
    path('institute/<int:pk>/edit', InstituteUpdateView.as_view(), name='institute_update'),
    path('institute/<int:pk>/delete', InstituteDeleteView.as_view(), name='institute_delete'),

    path('subject/add', SubjectCreateView.as_view(), name='subject_create'),
    path('subject/<int:pk>/edit', SubjectUpdateView.as_view(), name='subject_update'),
    path('subject/<int:pk>/delete', SubjectDeleteView.as_view(), name='subject_delete'),

    path('language/add', LanguageCreateView.as_view(), name='language_create'),
    path('language/<int:pk>/edit', LanguageUpdateView.as_view(), name='language_update'),
    path('language/<int:pk>/delete', LanguageDeleteView.as_view(), name='language_delete'),

    path('error_page/', ErrorPageView.as_view(), name='error_page'),
]

thesis_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("thesis.urls"),name="thesis"),
    path("", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    
]

thesis/views.py
from django.db.models.deletion import ProtectedError
from django.db.models import Q
from django.views.generic import ListView, DetailView
from thesis.forms import InstituteForm, LanguageForm, SubjectForm, UniversityForm, PersonForm, ThesisForm, SearchForm,  RegistrationForm
from .models import Institute, Language, Person, Subject, Thesis, ThesisKeyword, ThesisSubject, Type, University
from django.shortcuts import redirect, render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.http import HttpResponseRedirect, HttpResponseServerError
from django.views.generic import TemplateView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin


class InstituteListView(ListView):
    model = Institute
    template_name = 'institute_list.html'

class InstituteDetailView(DetailView):
    model = Institute
    template_name = 'institute_detail.html'

class LanguageListView(ListView):
    model = Language
    template_name = 'language_list.html'

class LanguageDetailView(DetailView):
    model = Language
    template_name = 'language_detail.html'

class PersonListView(ListView):
    model = Person
    template_name = 'person_list.html'

class PersonDetailView(DetailView):
    model = Person 
    template_name = 'person_detail.html'

class SubjectListView(ListView):
    model = Subject
    template_name = 'subject_list.html'

class SubjectDetailView(DetailView):
    model = Subject
    template_name = 'subject_detail.html'

class ThesisListView(ListView):
    model = Thesis
    template_name = 'thesis_list.html'

class ThesisDetailView(DetailView):
    model = Thesis
    template_name = 'thesis_detail.html'

class ThesisKeywordListView(ListView):
    model = ThesisKeyword
    template_name = 'thesiskeyword_list.html'

class ThesisKeywordDetailView(DetailView):
    model = ThesisKeyword
    template_name = 'thesiskeyword_detail.html'

class ThesisSubjectListView(ListView):
    model = ThesisSubject
    template_name = 'thesissubject_list.html'

class ThesisSubjectDetailView(DetailView):
    model = ThesisSubject
    template_name = 'thesissubject_detail.html'

class TypeListView(ListView):
    model = Type
    template_name = 'type_list.html'

class TypeDetailView(DetailView):
    model = Type
    template_name = 'type_detail.html'

class UniversityListView(ListView):
    model = University
    template_name = 'university_list.html'

class UniversityDetailView(DetailView):
    model = University
    template_name = 'university_detail.html'

def main(request):
    return render(request, 'main.html')

# def login_view(request):
#     form = LoginForm(request.POST or None)
#     context = {}
#     context['form'] = form
#     return render(request, 'login.html', context)

def sign_up(request):
    print("view")
    if request.method == 'POST':
        print("post")
        form = RegistrationForm(request.POST)
        if form.is_valid():
            print("valid")
            user = form.save()
            login(request, user)
            return redirect('/search')
    else:
        print("get")
        form = RegistrationForm()
        context = {}
        context['form'] = form
        return render(request, 'sign_up.html', context)


def search_view(request):
    context = {}
    changed = False
    if request.method == 'GET':
        form = SearchForm(request.GET)  
        if form.is_valid():
            thesis_no = form.cleaned_data['thesisno']
            title = form.cleaned_data['title']
            author = form.cleaned_data['author']
            superviser = form.cleaned_data['superviser']
            cosuperviser = form.cleaned_data['cosuperviser']
            type = form.cleaned_data['type']
            language = form.cleaned_data['language']
            university = form.cleaned_data['university']
            institute = form.cleaned_data['institute']
            submission_beginning_date = form.cleaned_data['submission_beginning_date']
            submission_ending_date = form.cleaned_data['submission_ending_date']
            number_of_pages_max = form.cleaned_data['number_of_pages_max']
            number_of_pages_min = form.cleaned_data['number_of_pages_min']
            years_choice = form.cleaned_data['years_choice']
            year = form.cleaned_data['year']
            keywords = form.cleaned_data['keywords']
            results = None
            thesis = Thesis.objects.all()

            if thesis_no != None and int(thesis_no) < 1000000:
                thesis = thesis.filter(thesis_no=thesis_no) 
                changed = True
            if title != None and title != '':
                thesis = thesis.filter(title__icontains=title)
                changed = True
            if author != None:
                thesis = thesis.filter(author=author)
                changed = True
            if superviser != None:
                thesis = thesis.filter(superviser=superviser)
                changed = True
            if cosuperviser != None:
                thesis = thesis.filter(cosuperviser=cosuperviser)
                changed = True
            if type != None:
                thesis = thesis.filter(type=type)
                changed = True
            if language != None:
                thesis = thesis.filter(language=language)
                changed = True
            if university != None:
                if institute != None:
                    thesis = thesis.filter(university=university, institute__name__contains=institute.name) #TODO maybe instead of this make user choose institute in the form
                thesis = thesis.filter(university=university)
                changed = True
            if institute != None:
                thesis = thesis.filter(institute__name__contains=institute.name)
                changed = True
            if submission_beginning_date != None:
                thesis = thesis.filter(submission_date__gte=submission_beginning_date)
                changed = True
            if submission_ending_date != None:
                thesis = thesis.filter(submission_date__lte=submission_ending_date)
                changed = True
            if number_of_pages_max != None:
                thesis = thesis.filter(number_of_pages__lte=number_of_pages_max)
                changed = True
            if number_of_pages_min != None:
                thesis = thesis.filter(number_of_pages__gte=number_of_pages_min)
                changed = True 
            if years_choice != None:
                if year != None:
                    if years_choice == 'at_this_date':
                        thesis = thesis.filter(year=year)
                    elif years_choice == 'before_this_date':
                        thesis = thesis.filter(year__lte=year)
                    elif years_choice == 'after_this_date':
                        thesis = thesis.filter(year__gte=year)
                    changed = True
            if keywords != None and keywords != '':
                keywords = keywords.split(',')
                q_objects = Q()
                for keyword in keywords:
                    q_objects |= Q(thesiskeyword__keyword__icontains=keyword)
                thesis = thesis.filter(q_objects).distinct()
                changed = True
                                    
    if changed == False:
        thesis = None
                                    
    results = thesis
    context['results'] = results #results will be a list of Thesis objects but for now it is None
    context['form'] = form


    return render(request, 'search_results.html', context)
 
# --- THESIS ---

class ThesisCreateView(LoginRequiredMixin,CreateView):
    model = Thesis
    template_name = 'thesis_form.html'
    form_class = ThesisForm
    success_url = '/thesis' 

class ThesisUpdateView(LoginRequiredMixin,UpdateView):
    model = Thesis
    template_name = 'thesis_form.html'
    form_class = ThesisForm
    success_url = '/thesis' 

class ThesisDeleteView(LoginRequiredMixin,DeleteView):
    model = Thesis
    template_name = 'delete_confirm.html'
    success_url = '/thesis' 

# --- PERSON ---

class PersonCreateView(LoginRequiredMixin,CreateView):
    model = Person
    template_name = 'person_form.html'
    form_class = PersonForm
    success_url = '/person' 

class PersonUpdateView(LoginRequiredMixin,UpdateView):
    model = Person
    template_name = 'person_form.html'
    form_class = PersonForm
    success_url = '/person' 

class PersonDeleteView(LoginRequiredMixin,DeleteView):
    model = Person
    template_name = 'delete_confirm.html'
    success_url = '/person' 

# --- UNIVERSITY --- 

class UniversityCreateView(LoginRequiredMixin,CreateView):
    model = University
    template_name =  'university_form.html'
    form_class = UniversityForm
    success_url = '/university'

class UniversityUpdateView(LoginRequiredMixin,UpdateView):
    model = University
    template_name =  'university_form.html'
    form_class = UniversityForm
    success_url = '/university'

class UniversityDeleteView(LoginRequiredMixin,DeleteView):
    model = University
    template_name = 'delete_confirm.html'
    success_url = '/university/' 

# --- INSTITUTE --- 

class InstituteCreateView(LoginRequiredMixin,CreateView):
    model = Institute
    template_name =  'institute_form.html'
    form_class = InstituteForm
    success_url = '/institute'

class InstituteUpdateView(LoginRequiredMixin,UpdateView):
    model = Institute
    template_name =  'institute_form.html'
    form_class = InstituteForm
    success_url = '/institute'

class InstituteDeleteView(LoginRequiredMixin,DeleteView):
    model = Institute
    template_name = 'delete_confirm.html'
    success_url = '/institute/'

# --- SUBJECT ---
    
class SubjectCreateView(LoginRequiredMixin,CreateView):
    model = Subject
    template_name =  'subject_form.html'
    form_class = SubjectForm
    success_url = '/subject'

thesis/templates/delete_confirm.html
{% include "header.html"%}

{% block content %}
  <h1>Confirm Delete</h1>
  <p>Are you sure you want to delete this entry?</p>
  <form method="post">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Confirm">
  </form>
{% endblock %}

thesis/templates/institute_detail.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<head>
    <title>Institute Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<body>
    <h1>Institute Detail</h1>
    <ul class="custom-ul">
    <li class="custom-li"><strong>Name: </strong>{{ object }}</li>
    </ul>
</body>
    <a href="{% url 'thesis:institute_update' pk=object.institute_id %}" class="custom-link">Edit Institute</a>
    <a href="{% url 'thesis:institute_delete' pk=object.institute_id %}" class="custom-link">Delete Institute</a>
</html>

thesis/templates/language_detail.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<head>
    <title>Language Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<body>
    <h1>Language Detail</h1>
    <ul class="custom-ul">
    <li class="custom-li"><strong>Name: </strong>{{ object.language_name }}</li>
    </ul>
</body>
    <a href="{% url 'thesis:language_update' pk=object.language_id %}" class="custom-link">Edit Language</a>
    <a href="{% url 'thesis:language_delete' pk=object.language_id %}" class="custom-link">Delete Language</a>
</html>

thesis/templates/person_form.html
{% include "header.html"%}

{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">

{% block content %}
  <h2>{% if form.instance.pk %}Edit Person{% else %}Add Person{% endif %}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

thesis/templates/person_list.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/list2.css' %}">
</head>
<body>
    <h1>Person List</h1>
    <h3> Click the item you want to see details about </h3>
    <nav class="custom-nav">
        <ul class="custom-ul">
            {% for person in object_list %}
            <li class="custom-li"><a href="{% url 'thesis:person-detail' pk=person.pk %}" class="custom-link">{{ person.name }} {{ person.surname }}</a></li>
            {% endfor %}
        </ul>
    </nav>
    <a href="{% url 'thesis:person_add' %}" class="custom-add-btn">Add Person</a>
</body>
</html>

thesis/templates/subject_detail.html
{% include "header.html"%}
<!DOCTYPE html>
<html>
<head>
    <title>Subject Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<body>
    <h1>Subject Detail</h1>
    <ul class="custom-ul">
    <li class="custom-li"><strong>Topic: </strong>{{ object.topic }}</li>
    <!-- Add more details as needed -->
    </ul>
</body>
    <a href="{% url 'thesis:subject_update' pk=object.subject_id %}" class="custom-link">Edit Subject</a>
    <a href="{% url 'thesis:subject_delete' pk=object.subject_id %}" class="custom-link">Delete Subject</a>
</html>

thesis/templates/subject_form.html
{% include "header.html"%}

{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">

{% block content %}
  <h2>{% if form.instance.pk %}Edit Subject{% else %}Add Subject{% endif %}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

thesis/templates/subject_list.html
{% include "header.html"%}
<!DOCTYPE html>
<html>
<head>
    <title>Subject List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/list2.css' %}"> 
</head>
<body>
    <h1>Subject List</h1>
    <h3> Click the item you want to see details about </h3>
    <nav class="custom-nav">
        <ul class="custom-ul">
        {% for subject in object_list %}
        <li class="custom-li"><a href="{% url 'thesis:subject-detail' pk=subject.pk %}" class="custom-link">{{ subject.topic }}</a></li>
        {% endfor %}
    </ul>
</nav>
    <a href="{% url 'thesis:subject_create' %}" class="custom-add-btn">Add Subject</a>
</body>
</html>

thesis/templates/thesis_form.html
{% include "header.html"%}

{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">

{% block content %}
  <h2>{% if form.instance.pk %}Edit Thesis{% else %}Add Thesis{% endif %}</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

thesis/templates/thesis_list.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<head>
    <title>Thesis List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/list2.css' %}"> 
</head>
<body>
    <h1>Thesis List</h1>
    <h3> Click the item you want to see details about </h3>
    <nav class="custom-nav">
    <ul class="custom-ul">
        {% for thesis in object_list %}
            <li class="custom-li"><a href="{% url 'thesis:thesis-detail' pk=thesis.pk %}" class="custom-link">{{ thesis.title }}</a></li>
        {% endfor %}
    </ul>
    </nav>
    <a href="{% url 'thesis:thesis_add' %}" class="custom-add-btn">Add Thesis</a>
</body>
</html>

thesis/templates/thesis_subject_detail.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<head>
    <title>Thesis Subject Detail</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
</head>
<body>
    <h1>Thesis Subject Detail</h1>
    <p>Subject: {{ object.subject.topic }}</p>
    <!-- Add more details as needed -->
</body>
</html>

thesis/templates/thesis_subject_list.html
{% include "header.html"%}

<html>
<head>
    <title>Thesis Subject List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/list.css' %}"> 
</head>
<body>
    <h1>Thesis Subject List</h1>
    <ul>
        {% for subject in object_list %}
            <li><a href="{% url 'thesis:thesissubject-detail' pk=subject.pk %}">{{ subject.subject.topic }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>

thesis/templates/university_form.html
{% include "header.html"%}

{% load static %}
<link rel="stylesheet" href="{% static 'css/form.css' %}">


{% block content %}
  <h2>Add University</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

thesis/templates/university_list.html
{% include "header.html"%}

<!DOCTYPE html>
<html>
<head>
    <title>University List</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/list2.css' %}"> 
</head>
<body>
    <h1>University List</h1>
    <h3> Click the item you want see details about </h3>
    <nav class="custom-nav">
        <ul class="custom-ul">
        {% for university in object_list %}
        <li class="custom-li"><a href="{% url 'thesis:university-detail' pk=university.pk %}" class="custom-link">{{ university.name }}</a></li>
        {% endfor %}
    </ul>  </nav>
    <a href="{% url 'thesis:university_create' %}" class="custom-add-btn">Add University</a>
</body>
</html>